2020-07-03 14:06:30,487 ERROR: Exception on /auth/reset_password_request [GET] [in /Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/auth/routes.py", line 71, in reset_password_request
    return render_template('auth.reset_password_request.html',
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: auth.reset_password_request.html
2020-07-03 14:07:14,151 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:75]
2020-07-03 14:07:23,628 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/auth/routes.py", line 68, in reset_password_request
    send_password_reset_email(user)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/auth/email.py", line 7, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/Users/justinlabrash/Documents/flask_project/flask_app/models.py", line 65, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
NameError: name 'app' is not defined
2020-07-03 14:07:54,549 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:75]
2020-07-03 14:07:59,743 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/auth/routes.py", line 68, in reset_password_request
    send_password_reset_email(user)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/auth/email.py", line 11, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/email/reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-07-03 14:09:29,121 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:75]
