2020-07-03 11:26:48,482 ERROR: Exception on /explore [GET] [in /Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/main/routes.py", line 46, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
AttributeError: type object 'Post' has no attribute 'timestamp'
2020-07-03 11:27:33,677 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:75]
2020-07-03 11:28:04,186 ERROR: Exception on /explore [GET] [in /Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/main/routes.py", line 52, in explore
    return render_template('index.html', title=_('Explore'),
NameError: name '_' is not defined
2020-07-03 11:28:21,118 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:75]
2020-07-03 11:28:30,961 ERROR: Exception on /user/jwilliams102 [GET] [in /Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/main/routes.py", line 69, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/justinlabrash/Documents/flask_project/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/justinlabrash/Documents/flask_project/flask_app/templates/user.html", line 10, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-07-03 11:29:58,672 INFO: Microblog startup [in /Users/justinlabrash/Documents/flask_project/flask_app/__init__.py:75]
